// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe4PI-vQZugUZJIEKHir66rdaw0Pszj0k',
    appId: '1:741485136216:web:aaf1553202345a0d7a7d2d',
    messagingSenderId: '741485136216',
    projectId: 'test-course-99493',
    authDomain: 'test-course-99493.firebaseapp.com',
    storageBucket: 'test-course-99493.appspot.com',
    measurementId: 'G-EXVQ61FK6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcX4tkFiJT3Bjd_oM7XFJTrkB4G8hHge0',
    appId: '1:741485136216:android:f546ca3cd3ac140d7a7d2d',
    messagingSenderId: '741485136216',
    projectId: 'test-course-99493',
    storageBucket: 'test-course-99493.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaQXKw4i6OftXJwPnfKbFywrbaYMfbCoc',
    appId: '1:741485136216:ios:644f037df0f5ef467a7d2d',
    messagingSenderId: '741485136216',
    projectId: 'test-course-99493',
    storageBucket: 'test-course-99493.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaQXKw4i6OftXJwPnfKbFywrbaYMfbCoc',
    appId: '1:741485136216:ios:644f037df0f5ef467a7d2d',
    messagingSenderId: '741485136216',
    projectId: 'test-course-99493',
    storageBucket: 'test-course-99493.appspot.com',
    iosBundleId: 'com.example.untitled',
  );
}
